version: "3.9"
services:
  igpost:
    build: .
    container_name: igpost
    ports:
      - "8000:8000"
    volumes:
      - ./sessions:/sessions
      - /mnt/c:/uploads:ro  # Mount Windows C: drive as read-only
    restart: unless-stopped
